# Création de containers Docker
# https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
stages:
  - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.6.0-debug
    entrypoint: [""]
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    CACHE_REPO: $CI_REGISTRY_IMAGE/cache
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - echo $CI_REGISTRY_IMAGE - $CI_COMMIT_REF_SLUG - $IMAGE_TAG - $CACHE_REPO - $CI_REGISTRY_USER - $CI_REGISTRY_PASSWORD - $CI_PROJECT_DIR - $CI_REGISTRY
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --cache=true --cache-repo=$CACHE_REPO --destination $CI_REGISTRY_IMAGE
